---
title: "Practical session on ISwR::cystfibr dataset"
author: "Florent Chuffart & Nicolas Glade"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---



```{r, echo=FALSE, eval=TRUE, label="loading libraries"}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
```
# Loading data

```{r echo=TRUE, results="verbatim"}
d = ISwR::cystfibr
head(d)
dim(d)
# removing sex
x = d[,-2]
```

# Pairwise plots

```{r echo=TRUE, results="verbatim"}
pairs(x, gap=0)
lattice::levelplot(abs(cor(x)))
hist(x$bmp)
```

# K-means

```{r echo=TRUE, results="verbatim"}
for (centers in 2:5) {
  for (i in 1:3) {
    k = kmeans(x, centers=centers);  pairs(x, gap=0, col=k$cluster, main=paste0("centers=", centers))
  }
}

cs = rep(2:20, each=100)
res = sapply(cs, function(c) {
  k = kmeans(x, centers=c);  
  ret = k$betweenss / k$totss
  return(ret)
})
plot(jitter(cs), jitter(res))
```

# PCA

```{r}
k2 = kmeans(x, centers=2)
set.seed(1)
k3 = kmeans(x, centers=3)
k3
k4 = kmeans(x, centers=4)
k4

# reduce the matrice (normalization)
mat = x
pca = prcomp(mat, scale=TRUE)
v = pca$sdev * pca$sdev
p = v / sum(v) * 100


layout(matrix(1:6,2), respect=TRUE)
# layout(matrix(1:2,1), respect=TRUE)
barplot(p)

for (i in 1:5) {
  j = i+1
  plot(pca$x[,i], pca$x[,j], xlab=paste0("PC", i, "(", signif(p[i], 3), "%)"), ylab=paste0("PC", j, "(", signif(p[j], 3), "%)"), pch=16, col=k2$cluster)  
}

for (i in 1:6) {  
  barplot(pca$rotation[,1], main=paste("PC", i, "(", signif(p[i], 3), "%)", sep=""))
}
# If paste0 do not exists: 
# paste0 = paste(sep="", ...)
```

# ANOVA 




# Discussion

...


# Session Information

```{r, results="verbatim"}
sessionInfo()
```

